---
# tasks file for git-download-mantis

- name: "Install Git and other needed packages"
  apt: name={{ item }}
  with_items: 
  - git
  - php7.0-mbstring
  - php7.0-mysql
  - libapache2-mod-php7.0
  - php7.0-bcmath
  - php7.0-intl
  - php7.0-json
  - php7.0-mcrypt
  - php7.0-mysql
  - php7.0-odbc
  - php7.0-zip
  - php7.0-soap
  - php7.0-gd
  notify: 
  - restart-apache

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: MySQLi
    option: mysqli.allow_local_infile
    value: 0

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: memory_limit
    value: 756M

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: post_max_size
    value: 64M

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: upload_max_filesize
    value: 64M

- name: "Clearing out existing web directory"
  file: 
    state: absent 
    path: "{{ web_files_path }}/"

- name: "Re-creating html directory"
  file:
    path: "{{ web_files_path }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0644
    recurse: yes

- name: "Git clone the Mantis BT repo"
  command: git clone {{ git_repo }} html
  args: 
    chdir: "{{ web_files_path }}/.."

- name: "Checkout the desired release"
  command: git checkout {{ tagged_release_version }}
  args: 
    chdir: "{{ web_files_path }}"

- name: "Install Composer program"
  script: ../files/install_composer.sh
  args: 
    creates: /usr/local/bin/composer

- name: "Install Composer packages"
  composer: 
    command: install
    working_dir: "{{ web_files_path }}"

- name: "Copying over config file"
  template:
    src: ../templates/config_inc.php.sample
    dest: "{{ web_files_path }}/config/config_inc.php.sample"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755

- name: "Setting ownership and permissions for web directory"
  file:
    path: "{{ web_files_path }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    recurse: yes

- name: "Removing Git folder from web server permissions"
  file:
    path: "{{ web_files_path }}/.git"
    state: directory
    owner: root
    group: root
    mode: 0640
    recurse: yes

- name: "Removing .gitignore from web server permissions"
  file:
    path: "{{ web_files_path }}/.gitignore"
    state: file
    owner: root
    group: root
    mode: 0640

