<?php
$g_hostname               = 'localhost';
$g_db_type                = 'mysqli';
$g_database_name          = '{{ git_download_mantis_configure_db_name }}';
$g_db_username            = '{{ git_download_mantis_configure_db_user }}';
$g_db_password            = '{{ git_download_mantis_configure_db_password }}';

$g_default_timezone       = 'UTC';

# This will be autogenerated by Mantis if going through the installation process
$g_crypto_master_salt     = 'qIJ0yv/vjO1ZKQccrLPROR8f4BphLV2vlI79Mzem3MA=';
